version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    volumes:
      - ./docker/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - nestjs
networks:
  nestjs:
volumes:
  db-data: